### ISSUE TITLE
Setup at http://book.costoffreedom.cc/

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom-book#1]
Should redirect to gibook.com/costoffreedom/costoffreedom-book

**Comment by mlinksva** [comment]
The full URL appears to be https://www.gitbook.com/book/costoffreedom/costoffreedom-book/details

What is needed to do this?

**Comment by mlinksva** [comment]
@clemsos http://book.costoffreedom.cc/ seems to work now. Not sure what you did but closing now.
