### ISSUE TITLE
Get a clean PDF using Latex 

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom-book#10]
Following #6 and the few options offered by gitbook regarding styling, it is way better to use Latex to generate a clean version for print.

This can be done already by using the `make pdf` command. It will first convert .md files to .tex following the order, then use the .cls Latex class and main file .tex in `/tex` folder to compile.

`latexmk` and `pandoc` are required

**Comment by clemsos** [comment]
[costoffreedom.pdf](https://github.com/costoffreedom/costoffreedom-book/files/193389/costoffreedom.pdf)

Current state of the build for reference. Maybe we can list all the problems - if there is too many :)

**Comment by mlinksva** [comment]
It looks nice! A few small things:
- CC license thing near front should say CC0
- Is there supposed to be a period before chapter numbers?
- internal links don't seem to work

**Comment by clemsos** [comment]
still TODO
- sans serif font
- fix image
- internal links
- appendix (needed ?)
- weird titles hierarchy in PDF nav

**Comment by hellekin** [comment]
On 04/27/2016 08:49 AM, Clément Renaud wrote:

> still TODO
> - sans serif font

OpenSans is nice and stable.

> - fix image
> - internal links
> - appendix (needed ?)

Why not?

> - weird titles hierarchy in PDF nav 

Do you need any help on all this or is it just for your personal action
list?

# 

## hk

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by clemsos** [comment]
I am struggling to set up the default font to sans serif... Latex is driving me crazy again.

This was more a personal list of things to do but any help is definitely welcome. 

What will be very useful is to double-check the PDF and list all the issues. Here is the latest build
[costoffreedom.pdf](https://github.com/costoffreedom/costoffreedom-book/files/240585/costoffreedom.pdf)

**Comment by clemsos** [comment]
ok solved the thing with sans serif ! small victory after 2h of pain  haha

**Comment by clemsos** [comment]
- [x] sans serif font
- [x]  ~~internal links~~ (not going to work on latex/PDF, sorry)
- [x] appendix 
- [x] weird titles hierarchy in PDF nav
- [x] fix bassel image size
- [x] author names placement
- [x] ~~TOC in sans serif~~ (does not look good) 
- [x] proper links for twitter handle (not recognized by pandoc)  
- [x] support for Chinese text
- [x] support for Arabic text

**Comment by clemsos** [comment]
OK here is the latest version, [costoffreedom.pdf](https://github.com/costoffreedom/costoffreedom-book/files/240976/costoffreedom.pdf)

we are almost there ! 

Still some minor problems to solve before releasing this final version (mostly small hyphenations and pagination maybe) . I have added the .tex files in the rep (2b5d818) so everyone can directly make changes in those files.

Any help is welcome @hellekin @christopheradams @mlinksva @rejon

**Comment by mlinksva** [comment]
It's looking great! I'll go through page by page later, but I noticed a couple things immediately:

**1**

> ⃝ CC Creative Commons 1.0 (CC0)

"Creative Commons 1.0" doesn't make any sense. If you want to spell something out, I'd suggest one of:

> Creative Commons Zero 1.0 (CC0)

or

> Dedicated to the public domain (CC0-1.0)

**2**

Links to author bios in chapter underneath chapter title don't work, point to attribution.html should be an internal link.

**Comment by clemsos** [comment]
thanks Mike, 8aa29c1 fix authors hyperlinks

For CC mention, how about this ?
![selection_111](https://cloud.githubusercontent.com/assets/743246/14894626/cc487f16-0d74-11e6-917d-77e96b07787e.png)

**Comment by mlinksva** [comment]
That's good. Should it say 2015, 2016, ? There aren't substantive changes made this year, but there's probably something that would clear very low copyright bar anyway.

**Comment by clemsos** [comment]
ok here is the latest PDF version. Let me know if there is change, then we can upload it to Lulu

[costoffreedom.pdf](https://github.com/costoffreedom/costoffreedom-book/files/242000/costoffreedom.pdf)

**Comment by mlinksva** [comment]
I found and fixed a stray dash in 595a59365bb0a1ad8507db0afb4ab0eee4dc8f57

On the attributions page all contributors but the first have a first line indent. Maybe intended.

Is the cover not included in the PDF?

Overall looks fantastic!

**Comment by clemsos** [comment]
OK thanks ! The cover is not included because it has to be printed separately - on Lulu for instance. I will make a final version with the cover of course.

**Comment by clemsos** [comment]
You know what ? let's ship it. I am finally closing this ! yeah
