### ISSUE TITLE
double or triple printing of contributor bios

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom-book#3]
Contributors are listed with bios
- bottom of each chapter
- at end in contributor list
- gratuitously again, one page for each contributor

At least the 3rd ought go.

I suggest the bio could appear just once, either in the first or second, probably second. Name(s) only for chapters.

**Comment by hellekin** [comment]
On 12/28/2015 05:42 PM, Mike Linksvayer wrote:

> Contributors are listed with bios
> - bottom of each chapter
> - at end in contributor list
> - gratuitously again, one page for each contributor
> 
> At least the 3rd ought go.
> 
> I suggest the bio could appear just once, either in the first or second,
> probably second. Name(s) only for chapters.

The bio is supposed to appear with the first contribution, then only the
name is mentioned.  This was the case in the original publication.

# 

hk

## 

 _ _     We are free to share code and we code to share freedom
(_X_)yne Foundation, Free Culture Foundry \* https://www.dyne.org/donate/

**Comment by clemsos** [comment]
agree. bio once then names is better

**Comment by mlinksva** [comment]
I see the logic in the scheme used, but seems to be harder to maintain (I see there's a script) and optimized for a linear read of the book. I think I'd prefer names only in the chapters, and author+bios all in one place, and without page breaks between each one. If nobody objects or does it first I'll implement this in the next days.

**Comment by clemsos** [comment]
@mlinksva sorry for the late answer. Go for it, looks like the best solution to me as well.

**Comment by mlinksva** [comment]
Completed.
