### ISSUE TITLE
pdf.css

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom-book#4]
The rendered pdf https://www.gitbook.com/download/pdf/book/costoffreedom/costoffreedom-book has two behaviors I'd like to get rid of:
- In the table of contents, displays (filename.html) next to each entry. I guess this could be useful for debugging purposes but doesn't help readers.
- Chapter titles are shown twice, probably once as specified in chapter markdown title, once as specified in SUMMARY.md

Both of these behaviors are probably specified in `pdf.css` -- if I rename it, they both go away. But I can't figure out what in `pdf.css` specifies those behaviors. `pdf.css` seems to be very complicated, I suspect ought be blanked except for some minimum styles we explicitly want. @clemsos it looks like you created the `pdf.css`. I'm probably missing some obvious things. Thoughts?

**Comment by clemsos** [comment]
@mlinksva yes, this `pdf.css` is hellish indeed ! I think I imported it from the booktype but most of it is useless. I managed to remove the link ( see 24f4e5b0c770c0948bbdc83f669166f03153c025 ) but no idea about the chapter titles . It is very hard to debug this PDF css thing as there is no control on how it really works. Let's just drop the `pdf.css`. I pushed a minimum version of the file (that could even be reduced even more) so we can see more clearly what it does.
