### ISSUE TITLE
Get generated EPUB to pass epubcheck

### ISSUE THREAD

**Issue by christopheradams** [costoffreedom/costoffreedom-book#5]
To get an EPUB accepted at most online retailers, it has to pass a validation step. You can test an EPUB locally using [epubcheck](https://github.com/IDPF/epubcheck).

Unfortunately gitbook does not always generate error-free EPUB files, mostly due to the markdown parser not writing valid XHTML in some edge cases (e.g., footnotes, heading id's).

Assuming you've installed gitbook-cli, and cloned this book in your home directory, and downloaded epubcheck:

```
cd costoffreedom-book
gitbook epub . ~/costoffreedom.epub

cd ~/epubcheck-4.0.1
java -jar epubcheck.jar -out ~/epubcheck.xml ~/costoffreedom.epub
```

Here's the output:

[costoffreedom-epubcheck.xml.txt](https://github.com/costoffreedom/costoffreedom-book/files/140296/costoffreedom-epubcheck.xml.txt)

**Comment by christopheradams** [comment]
- [x] fix heading id's in epilogue/andromeda-report (the id="" starts with a number)
- [x] fix internal links
- [x] workaround for footnotes
- [x] fix warning for Non-registered URI scheme types

The last one might not actually be a problem. It looks like this:

```
Validating using EPUB version 2.0.1 rules.
WARNING(HTM-025): /home/christopher/Desktop/costoffreedom.epub/online-resources.html(46,137): Non-registered URI scheme type found in href.
WARNING(HTM-025): /home/christopher/Desktop/costoffreedom.epub/prologue-introduction.html(54,104): Non-registered URI scheme type found in href.
```

**Comment by clemsos** [comment]
Finally get the time to reproduce the epub generation, works well ! but I just tried to upload to Lulu.com and it still fail. any idea ?

**Comment by clemsos** [comment]
the "Non-registered URI scheme types" was related to a markdown links notation that was not supported. Now the epub generated with gibook is "Validated using EpubCheck version 4.0.1." :)

**Comment by christopheradams** [comment]
On 03/06/2016 07:25 AM, Clément Renaud wrote:

> Finally get the time to reproduce the epub generation, works well ! but
> I just tried to upload to Lulu.com and it still fail. any idea ?

Are you using the custom version of gitbook I made? (See the README)

If epubcheck validates the book but Lulu still doesn't accept it, I'm
not sure.

**Comment by clemsos** [comment]
ok a bit of pain here. made a script to add required metadata then it worked
