### ISSUE TITLE
Font and overall apperance of published result is quite ugly

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom-book#6]
Maybe we could port the work Julien did on the first version of the book
 : https://github.com/costoffreedom/oldies/tree/master/original-book

**Comment by clemsos** [comment]
Looks like Gitbook didnt accept any custom fonts...  @christopheradams I remembered you said you were trying sth with latex no ?

**Comment by clemsos** [comment]
we can easily use latex to make a pdf using a cleaner template  with Pandoc  https://gist.github.com/clemsos/9e480b2b792b57f1b22d

**Comment by christopheradams** [comment]
Yes, pandoc works well for this task.

What I did for https://github.com/waiting4bassel/waiting-latex/ (see the
dev branch):
- add the gitbook repo as a subtree
- write a Makefile to convert the md files to tex
- write a custom latex preamble to format the book the way you want it
  (for costoffreedom you'd really want to parse SUMMARY.md to get the
  chapter names and section ordering right)

It's a fair amount of work.

**Comment by clemsos** [comment]
thanks for the heads up chris !

I throw basis for latex build with Makefile and basic md > tex conversion (using pandoc). Works fairly well. Just need to tweak the .cls Latex class to have a clean display. It is already looking waaaay better than the gitbook build :)  

Actually I saw the work you are doing on waiting4bassel book. Maybe we should merge efforts - or just debrief afterwards on all these publishing stuff.

**Comment by clemsos** [comment]
consider this solved by #10 . closing
