### ISSUE TITLE
get ISBN ?

### ISSUE THREAD

**Issue by clemsos** [costoffreedom/costoffreedom-book#7]
looks like a requirement for Lulu and will officially make it a book :)

@christopheradams any idea of how to do it ?

**Comment by christopheradams** [comment]
There should be an option to let Lulu assign one.

**Comment by clemsos** [comment]
ok ISBN is 978-1-365-08698-4

**Comment by mlinksva** [comment]
Added to https://www.wikidata.org/wiki/Q21486039 cc https://github.com/costoffreedom/costoffreedom.cc/issues/36
