### ISSUE TITLE
Images removed from book

### ISSUE THREAD

**Issue by mlinksva** [costoffreedom/costoffreedom-book#8]
@clemsos you deleted all the images with dc74ac4702b5284fd7d74abfa3ba828726016457 ... the chaper tocs had them, and the collective-memory free bassel chapter consisted of only an image. Was this intentional?

**Comment by clemsos** [comment]
Not really intentional. It was part of the process to unify the formatting. Having isolated images in non-chapters files didn't really make sense but I agree that this was not a careful move. Going to bring the images back now.
