### ISSUE TITLE
consider new cover or updated cover for new edition

### ISSUE THREAD

**Issue by ghost** [costoffreedom/costoffreedom-book#9]
improved red? or black with white painting or new cover al together? new one should stand out from the released version

**Comment by clemsos** [comment]
what about this ? I say we keep the same cover. It is current for books to have multiple releases with the same cover. Maybe we should add a note saying "2nd edition" somewhere.

**Comment by mlinksva** [comment]
I agree with keeping the same cover. There aren't any substantive changes. Not sure "2nd edition" is even the right characterization, implies too big a change. 2nd printing? Though printing is archaic. And reading https://en.wikipedia.org/wiki/Edition_(book) I guess my understanding is incorrect. Hmm.

**Comment by clemsos** [comment]
ok for keeping the cover then. closing

**Comment by hellekin** [comment]
On 04/28/2016 06:17 PM, Mike Linksvayer wrote:

> I agree with keeping the same cover. There aren't any substantive changes. Not sure "2nd edition" is even the right characterization, implies too big a change. 2nd printing? Though printing is archaic. And reading https://en.wikipedia.org/wiki/Edition_(book) I guess my understanding is incorrect. Hmm.

what about version 1.1.0?

**Comment by mlinksva** [comment]
A version number would be fine I suppose. I'd go for 1.0.1 though if we're going to look semver-ish -- bug fixes rather than new functionality, to the extent that concept can be translated.
